/**
 * REQ-0414 — developer live-token editor: registry + pure helpers.
 *
 * This module is the data layer behind the DEV-ONLY token editor panel
 * (`components/dev-token-editor`).  It is import-guarded by
 * `import.meta.env.DEV` at the mount site, so nothing here ships in an
 * end-user build.
 *
 * Design intent (REQ-0414 §1):
 *   - Controls are auto-generated by looping a declarative group registry;
 *     no per-token JSX is hand-written.
 *   - The item list is NOT hardcoded to fixed *values* — every current value
 *     is read live from the running document (see `dev-token-live.ts`), and
 *     the colour groups reconcile their membership against the variables
 *     actually declared on `:root` (`discoverRootVarNames` + `driftFor`) so a
 *     newly-added `--text-*` / `--surface-*` / `--border-*` / `--primary*`
 *     token surfaces automatically instead of going stale.
 *
 * All exports here are PURE (registry data + string maths).  DOM-touching
 * helpers (probe reads, `:root` overrides) live in `dev-token-live.ts` so the
 * conversions can be unit-tested without a browser.
 */

export type DevTokenKind = 'color' | 'size'

export interface DevTokenGroupSpec {
  /** Stable id (also used as React key). */
  id: string
  /** English label — this is a developer tool, so no i18n. */
  title: string
  kind: DevTokenKind
  /**
   * COLOR groups: ordered, curated member var names (without the leading
   * `--`).  Rendered in this order.  `discoverPrefixes` is used to detect
   * drift — any `:root` var matching a prefix but missing from `members`
   * is reported by `driftFor` and appended by `orderedColorMembers`.
   */
  members?: string[]
  discoverPrefixes?: string[]
  /**
   * SIZE groups: the Tailwind type-scale names.  Each is backed by a
   * `--fs-<name>` variable (see tailwind.config.ts, REQ-0414) and rendered
   * with the Tailwind class `text-<name>`.
   */
  sizes?: string[]
}

/**
 * The editable groups, matching REQ-0414 §1.  Font family is intentionally
 * absent — it is fixed to Noto Sans JP and shown read-only in the panel.
 */
export const DEV_TOKEN_GROUPS: readonly DevTokenGroupSpec[] = [
  {
    id: 'fontSize',
    title: 'Font size — type scale',
    kind: 'size',
    // REQ-0416 — scale collapsed 10 → 6 (label/callout/headline/heading merged).
    sizes: ['micro', 'caption', 'body-sm', 'body', 'title', 'display'],
  },
  {
    id: 'text',
    title: 'Text colors',
    kind: 'color',
    // REQ-0416 — text-faint removed (merged into disabled).
    members: [
      'text-primary',
      'text-secondary',
      'text-tertiary',
      'text-muted',
      'text-disabled',
      'text-inverse',
      'warning',
      'destructive',
      'info',
    ],
    discoverPrefixes: ['text-'],
  },
  {
    id: 'surface',
    title: 'Surface / background',
    kind: 'color',
    members: [
      'surface-0',
      'surface-1',
      'surface-2',
      'surface-3',
      'surface-4',
      'surface-inverse-0',
      'surface-inverse-1',
      'surface-inverse-2',
      'background',
      'card',
      'popover',
      'muted',
      'secondary',
    ],
    discoverPrefixes: ['surface-'],
  },
  {
    id: 'border',
    title: 'Borders',
    kind: 'color',
    members: ['border-default', 'border-strong', 'border-subtle'],
    discoverPrefixes: ['border-'],
  },
  {
    id: 'accent',
    title: 'Accent (primary)',
    kind: 'color',
    // REQ-0416 — primary-faint removed (merged into soft).
    members: [
      'primary',
      'primary-hover',
      'primary-active',
      'primary-soft',
      'primary-foreground',
    ],
    discoverPrefixes: ['primary'],
  },
] as const

/** The single fixed UI font family (REQ-0414 §1 — shown read-only). */
export const FIXED_FONT_FAMILY = 'Noto Sans JP'

/* -------------------------------------------------------------------------
 * Membership / drift reconciliation
 * ------------------------------------------------------------------------- */

/**
 * Scan every same-origin stylesheet for the BASE `:root` rule (not
 * `:root.light` / `:root[data-base=...]`) and collect the custom-property
 * names declared on it (without the leading `--`).
 *
 * Cross-origin sheets throw on `.cssRules` access — those are skipped.  Pass a
 * document for testing; defaults to the ambient `document`.
 */
export function discoverRootVarNames(doc: Document = document): string[] {
  const names = new Set<string>()
  for (const sheet of Array.from(doc.styleSheets)) {
    let rules: CSSRuleList | null = null
    try {
      rules = sheet.cssRules
    } catch {
      // Cross-origin / not-yet-loaded sheet — skip.
      continue
    }
    if (!rules) continue
    for (const rule of Array.from(rules)) {
      if (!isStyleRule(rule)) continue
      if (rule.selectorText !== ':root') continue
      const style = rule.style
      for (let i = 0; i < style.length; i++) {
        const prop = style.item(i)
        if (prop.startsWith('--')) names.add(prop.slice(2))
      }
    }
  }
  return Array.from(names)
}

function isStyleRule(rule: CSSRule): rule is CSSStyleRule {
  // `instanceof CSSStyleRule` is unavailable under jsdom; duck-type instead.
  return typeof (rule as CSSStyleRule).selectorText === 'string'
}

/**
 * Names declared on `:root` that match a colour group's `discoverPrefixes`
 * but are NOT in its curated `members` list — i.e. tokens the registry has
 * drifted behind.  Returned so the panel can append them and warn.
 */
export function driftFor(group: DevTokenGroupSpec, rootVarNames: readonly string[]): string[] {
  if (group.kind !== 'color' || !group.discoverPrefixes) return []
  const known = new Set(group.members ?? [])
  return rootVarNames
    .filter((n) => group.discoverPrefixes!.some((p) => n.startsWith(p)))
    .filter((n) => !known.has(n))
    .sort()
}

/**
 * The full ordered member list for a colour group: curated `members` first
 * (in their intended order), then any discovered drift appended.  This is
 * what the panel renders, so a freshly-added token appears without a code
 * change (REQ-0414 §1 "enumerate current tokens").
 */
export function orderedColorMembers(
  group: DevTokenGroupSpec,
  rootVarNames: readonly string[],
): string[] {
  const base = group.members ?? []
  return [...base, ...driftFor(group, rootVarNames)]
}

/* -------------------------------------------------------------------------
 * Colour conversions (pure)
 *
 * All editable colour tokens are stored as HSL *triplets* (e.g. `0 0% 96%`)
 * and consumed via `hsl(var(--x))`.  The panel's native colour input speaks
 * hex, so we convert both ways.  Writing back a triplet keeps every existing
 * `hsl(var(--x))` call-site working unchanged.
 * ------------------------------------------------------------------------- */

/** Clamp helper. */
function clamp(n: number, lo: number, hi: number): number {
  return Math.min(hi, Math.max(lo, n))
}

/** `rgb(250, 250, 250)` / `rgba(...)` → `#fafafa` (lowercase, 6-digit). */
export function rgbStringToHex(rgb: string): string | null {
  const m = rgb.match(/rgba?\(\s*([\d.]+)[,\s]+([\d.]+)[,\s]+([\d.]+)/i)
  if (!m) return null
  const to2 = (v: string) => clamp(Math.round(parseFloat(v)), 0, 255).toString(16).padStart(2, '0')
  return `#${to2(m[1])}${to2(m[2])}${to2(m[3])}`
}

/** `#fafafa` / `#fff` → `{ r, g, b }` (0–255), or null if malformed. */
export function hexToRgb(hex: string): { r: number; g: number; b: number } | null {
  let h = hex.trim().replace(/^#/, '')
  if (h.length === 3) h = h.split('').map((c) => c + c).join('')
  if (!/^[0-9a-fA-F]{6}$/.test(h)) return null
  return {
    r: parseInt(h.slice(0, 2), 16),
    g: parseInt(h.slice(2, 4), 16),
    b: parseInt(h.slice(4, 6), 16),
  }
}

/**
 * `#fafafa` → `"0 0% 98%"` (an HSL triplet ready for `hsl(var(--x))`).
 * H is integer degrees, S/L are integer percents — matching the authored
 * style in globals.css.
 */
export function hexToHslTriplet(hex: string): string | null {
  const rgb = hexToRgb(hex)
  if (!rgb) return null
  const r = rgb.r / 255
  const g = rgb.g / 255
  const b = rgb.b / 255
  const max = Math.max(r, g, b)
  const min = Math.min(r, g, b)
  const l = (max + min) / 2
  let h = 0
  let s = 0
  const d = max - min
  if (d !== 0) {
    s = d / (1 - Math.abs(2 * l - 1))
    switch (max) {
      case r:
        h = ((g - b) / d) % 6
        break
      case g:
        h = (b - r) / d + 2
        break
      default:
        h = (r - g) / d + 4
    }
    h *= 60
    if (h < 0) h += 360
  }
  const H = Math.round(h)
  const S = Math.round(s * 100)
  const L = Math.round(l * 100)
  return `${H} ${S}% ${L}%`
}

/**
 * `"0 0% 98%"` → `#fafafa`.  Used to seed the native colour input from a
 * raw authored triplet when the DOM probe is unavailable (e.g. tests).
 * Returns null if the string is not a plain `H S% L%` triplet.
 */
export function hslTripletToHex(triplet: string): string | null {
  const m = triplet.trim().match(/^([\d.]+)\s+([\d.]+)%\s+([\d.]+)%$/)
  if (!m) return null
  const h = parseFloat(m[1])
  const s = clamp(parseFloat(m[2]), 0, 100) / 100
  const l = clamp(parseFloat(m[3]), 0, 100) / 100
  const c = (1 - Math.abs(2 * l - 1)) * s
  const hp = (((h % 360) + 360) % 360) / 60
  const x = c * (1 - Math.abs((hp % 2) - 1))
  let r = 0
  let g = 0
  let b = 0
  if (hp < 1) [r, g, b] = [c, x, 0]
  else if (hp < 2) [r, g, b] = [x, c, 0]
  else if (hp < 3) [r, g, b] = [0, c, x]
  else if (hp < 4) [r, g, b] = [0, x, c]
  else if (hp < 5) [r, g, b] = [x, 0, c]
  else [r, g, b] = [c, 0, x]
  const m2 = l - c / 2
  const to2 = (v: number) => clamp(Math.round((v + m2) * 255), 0, 255).toString(16).padStart(2, '0')
  return `#${to2(r)}${to2(g)}${to2(b)}`
}

/** True for a bare `H S% L%` triplet (no `var()`, no `hsl()` wrapper). */
export function isHslTriplet(value: string): boolean {
  return /^[\d.]+\s+[\d.]+%\s+[\d.]+%$/.test(value.trim())
}

/* -------------------------------------------------------------------------
 * Export serialisation (pure)
 * ------------------------------------------------------------------------- */

export interface TokenSnapshot {
  /** colour token name (no `--`) → HSL triplet, e.g. `text-primary` → `0 0% 96%`. */
  colors: Record<string, string>
  /** type-scale name → `{ px, lineHeight }`, e.g. `micro` → `{ px: 10, lineHeight: '14px' }`. */
  sizes: Record<string, { px: number; lineHeight: string }>
}

/**
 * `:root` CSS block for globals.css — colour triplets plus `--fs-*` size
 * overrides.  Paste inside the base `:root { ... }`.
 */
export function serializeGlobalsCss(snap: TokenSnapshot): string {
  const lines: string[] = ['/* REQ-0414 dev-token-editor export */']
  for (const [name, triplet] of Object.entries(snap.colors)) {
    lines.push(`--${name}: ${triplet};`)
  }
  for (const [name, s] of Object.entries(snap.sizes)) {
    lines.push(`--fs-${name}: ${s.px}px;`)
  }
  return lines.join('\n')
}

/**
 * `fontSize: { ... }` tuples for tailwind.config.ts — each with the edited px
 * as the `var(--fs-<name>, <px>)` fallback, directly paste-able over the
 * existing block.
 */
export function serializeTailwindFontSize(snap: TokenSnapshot): string {
  const lines: string[] = ['// REQ-0414 dev-token-editor export — fontSize scale']
  for (const [name, s] of Object.entries(snap.sizes)) {
    const key = /^[a-z][a-z0-9]*$/.test(name) ? name : `'${name}'`
    lines.push(`${key}: ['var(--fs-${name}, ${s.px}px)', { lineHeight: '${s.lineHeight}' }],`)
  }
  return lines.join('\n')
}

/* -------------------------------------------------------------------------
 * REQ-0420 — token overlay / click-to-reassign inspector helpers (pure)
 * ------------------------------------------------------------------------- */

/** The type-scale tokens, small → large, as they appear in `text-<token>`. */
export const TYPE_SCALE_TOKENS = [
  'micro',
  'caption',
  'body-sm',
  'body',
  'title',
  'display',
] as const

export type TypeScaleToken = (typeof TYPE_SCALE_TOKENS)[number]

/** Distinct overlay colour per token (border + label chip). */
export const TOKEN_OVERLAY_COLORS: Record<TypeScaleToken, string> = {
  micro: '#6b7280', // gray-500
  caption: '#a855f7', // purple-500
  'body-sm': '#3b82f6', // blue-500
  body: '#22c55e', // green-500
  title: '#f59e0b', // amber-500
  display: '#ef4444', // red-500
}

/**
 * Which type-scale token a class list carries (first / most-specific match),
 * or null.  `body-sm` is tested before `body`; classes are exact so
 * `text-body-sm` never matches `text-body`.
 */
export function detectSizeToken(classes: readonly string[]): TypeScaleToken | null {
  for (const t of TYPE_SCALE_TOKENS) {
    if (classes.includes(`text-${t}`)) return t
  }
  return null
}

/** A recorded reassignment (element identity carried separately at runtime). */
export interface TokenReassignment {
  /** Trimmed, collapsed text content (locator hint for finding it in code). */
  text: string
  /** Short DOM path (tag[.class] chain) — a second locator hint. */
  path: string
  from: TypeScaleToken
  to: TypeScaleToken
}

/** Paste-back list of overlay reassignments for the human/CC to bake in code. */
export function serializeReassignments(changes: readonly TokenReassignment[]): string {
  if (changes.length === 0) return '// REQ-0420 — no reassignments yet'
  const lines = ['// REQ-0420 token overlay reassignments (element → from → to)']
  for (const c of changes) {
    lines.push(`- text-${c.from} → text-${c.to}  "${c.text}"  [${c.path}]`)
  }
  return lines.join('\n')
}
