import type { DownloadKind } from '../../shared/ipc-contracts'

/**
 * REQ-0241 — thrown when the main-side DownloadManager rejects a
 * start request because another download (model / GPU tool / font)
 * is already in flight.  The three renderer download services
 * (transcription.ts, gpu-tool.ts, font.ts) all throw this class,
 * and the UI components catch it to show a toast naming the active
 * kind + label so the user knows what to wait for.
 *
 * Lives in its own file to avoid a circular dependency between
 * `services/transcription.ts` and the other two service modules.
 */
export class DownloadBusyError extends Error {
  readonly activeKind: DownloadKind | 'unknown'
  readonly activeLabel: string
  constructor(activeKind: DownloadKind | 'unknown', activeLabel: string) {
    super(`Another download is in progress: ${activeKind} (${activeLabel})`)
    this.name = 'DownloadBusyError'
    this.activeKind = activeKind
    this.activeLabel = activeLabel
  }
}

/**
 * REQ-0241 — helper: convert the main-side ErrResult shape into a
 * DownloadBusyError when the code matches.  Returns null otherwise
 * so callers can chain to their existing generic Error path.
 *
 * The main handlers embed activeKind / activeLabel in the ErrResult
 * message string (`Another download is in progress: model (large-v3)`)
 * for logs; the DOWNLOAD_BUSY code is the machine-readable signal.
 * We re-parse the message to recover the kind/label pair — this is
 * a controlled string, generated by our own IPC handlers, so the
 * regex is safe.  Fallbacks to 'unknown' if the shape ever drifts.
 */
export function tryParseBusyError(
  err: { code: string; message: string } | undefined,
): DownloadBusyError | null {
  if (!err || err.code !== 'DOWNLOAD_BUSY') return null
  const m = /: (model|gpu-tool|font) \(([^)]+)\)/.exec(err.message)
  if (m) {
    return new DownloadBusyError(m[1] as DownloadKind, m[2])
  }
  return new DownloadBusyError('unknown', err.message)
}
